apiVersion: v1
kind: Service
metadata: 
  name: besu-validator
spec: 
  selector:
    app: besu-validator
  ports:
    - name: p2p-tcp
      protocol: TCP
      port: 30303 #p2p
      targetPort: 30303
    - name: p2p-udp
      protocol: UDP
      port: 30303
      targetPort: 30303
    - name: rpc
      protocol: TCP
      port: 8545 
      targetPort: 8545
    - name: metrics
      protocol: TCP
      port: 9545 #metrics
      targetPort: 9545
  type: ClusterIP